### ISSUE TITLE
Async feature violates additive property

### ISSUE THREAD

**Issue by kmicklas** [gsquire/sendgrid-rs#104]
Cargo features are [required to be additive](https://doc.rust-lang.org/cargo/reference/features.html?highlight=additive#feature-unification) to function properly when a crate is used transitively multiple times in a complete program.

The `async` feature violates this property by changing the type of `SGClient::send` in an incompatible way. Would it be possible to convert the async implementation to a separate method with its own name (or maybe make a different async client type)?

**Comment by gsquire** [comment]
If I am understanding your issue correctly, you have a program that depends on both versions of `SGClient::send`?

**Comment by kmicklas** [comment]
It's easy for me to work around this, but yes.

**Comment by gsquire** [comment]
I pushed up a branch that should help with this. Let me know if you are able to test it out.

**Comment by kmicklas** [comment]
#105 looks great, thank you!

**Comment by gsquire** [comment]
Published as version 0.20.0 now. Thanks for pointing this out!
