### ISSUE TITLE
Upgrade to SendGrid v3 Web API

### ISSUE THREAD

**Issue by thinkingserious** [gsquire/sendgrid-rs#12]
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thanks!

**Comment by gsquire** [comment]
I was going to make a tracking issue for V3, so thanks for adding this. I will start reading up on what needs to get done for this library.

**Comment by gsquire** [comment]
Could use this for JSON: https://github.com/maciejhirsz/json-rust

**Comment by gsquire** [comment]
@thinkingserious I have added basic V3 support. I will continue adding options on an as-needed basis as this is rather simple to do.
