### ISSUE TITLE
Return message id from v3 send API

### ISSUE THREAD

**Issue by philbooth** [gsquire/sendgrid-rs#23]
I need to access the message id returned by the v3 send API, but couldn't see a way to do it. Am I missing something?

To get something working in the meantime, I ended up making [a branch](https://github.com/gsquire/sendgrid-rs/compare/master...philbooth:message-id?expand=1) that returns it instead of the response status, getting the value out of the `X-Message-Id` header. Is there some version of that change that would be worth me tidying up and opening as a PR?

**Comment by gsquire** [comment]
Thanks for opening this issue. I have debated returning the `reqwest::Resposne` type and just re-exporting it. This would give the user access to the headers and other parts of the response. Would this suffice? If so, I will make a PR soon.

**Comment by philbooth** [comment]
> Would this suffice?

Yep, works for me!

**Comment by gsquire** [comment]
This was updated in version 0.7.0.
