### ISSUE TITLE
Implement an `add_headers` function to `Personalization` struct in V3

### ISSUE THREAD

**Issue by brizental** [gsquire/sendgrid-rs#25]
This is so that I can add custom x headers to my email messages.

I was thinking something like https://github.com/gsquire/sendgrid-rs/blob/master/src/v3.rs#L233-L244 that will receive a vector of headers as an argument, loop over that and add them one by one.

I'd be happy to send a PR for that, I just wanted to make sure that it's something that you guys agree with and if I got that right.

**Comment by gsquire** [comment]
Sure, I'd be happy to take a PR. Feel free to ping me if you need any help.
