### ISSUE TITLE
Use failure crate

### ISSUE THREAD

**Issue by gsquire** [gsquire/sendgrid-rs#29]
Migrate the error handling to the [failure](https://github.com/rust-lang-nursery/failure) crate.

CC @richo

**Comment by richo** [comment]
Thanks for the heads up. I've been thinking about this and one other thing (I'll open an issue in a sec) and I think that's probably enough for a release?

**Comment by gsquire** [comment]
I agree. I may also update the V3 API too so they have a little more parity.

**Comment by gsquire** [comment]
closed in #31
