### ISSUE TITLE
Unify setters on Mail and/or migrate to actual Builders

### ISSUE THREAD

**Issue by richo** [gsquire/sendgrid-rs#30]
What it says on the tin.

**Comment by richo** [comment]
I'm finally working on this.

I want  to migrate to a unified method for setting, To, From etc to remove the "You  must call add_to and add_to_name the same number of times" sharp edge from the API.

The question is, would you prefer an api that abstracts over the underlying Destination? Concretely:

```rust
let msg = Mail::new()
  .add_to(Destination { address: "text@example.org", name: "person mcfacerhaver" })
  .build();
```
or
```rust
let msg = Mail::new()
  .add_to("text@example.org", "person mcfacerhaver")
  .build();
```

I lean toward the second, but the first makes it easier to do  things like bcc yourself on outgoing mail for example.

**Comment by gsquire** [comment]
Sorry for a delayed response.

I like the second option as well. We may be even to take it a step further and have those parameters be separate types so there isn't any confusion on ordering.

```rust
let m = Mail::new().add_to(MailAddress("h@example.org"), MailName("First Last")).build();
```

It certainly adds more characters but it's clear how the arguments should be passed. These can just be tuple structs that dereference to string slices. What are your thoughts on that?

**Comment by gsquire** [comment]
Hey, @richo. No problem if you haven't made progress on this but I figured I would check in. Let me know if you need any help.

**Comment by otavio** [comment]
This does sound like a good API. I look forward to it.

**Comment by otavio** [comment]
News on this?

**Comment by gsquire** [comment]
I think I will work on the V3 API this weekend and hopefully get around to closing these issues out. I believe V2 is already handled in master.

**Comment by otavio** [comment]
Great. I look forward to a more expressive API in future.

**Comment by richo** [comment]
Hey, Sorry for not being more responsive on this one.

I spent a while thinking about this but didn't make a ton of forward progress. Potentially the most interesting thing I learned is that all the moves on the builder api aren't free (Althoguh now I'm struggling to find the great blog post I found with some benchmarks)

**Comment by gsquire** [comment]
Hey, no worries @richo. I should get around to posting a PR for this over the weekend and can CC you if you want to review. We can check into performance if that becomes an issue.
