### ISSUE TITLE
 Publish new patch version for reqwest upgrade

### ISSUE THREAD

**Issue by richerarc** [gsquire/sendgrid-rs#34]

**Comment by gsquire** [comment]
Are you asking to release a new version with reqwest 0.9? Unfortunately there are breaking changes in master right now and I had hoped to get one more update in before publishing 0.8.

Is there any cause for concern for using reqwest 0.8 currently?

**Comment by richerarc** [comment]
the main concern is the reqwest 0.8 has a dependency on openssl 0.9.24 which link to a old version of openssl and is not compatible with openssl 1.0> (see [sfackler/rust-openssl#987](https://github.com/sfackler/rust-openssl/issues/987)

**Comment by gsquire** [comment]
Ok that's fair. What I can do is create a branch based off of the last stable commit and push a patch version with reqwest 0.9. I'll post again here once crates.io has it.

Thanks for bringing this up.

**Comment by gsquire** [comment]
I pushed version 0.7.2 with reqwest 0.9. Please open another issue if you run into problems.
