### ISSUE TITLE
V3 structures should be easier to construct 

### ISSUE THREAD

**Issue by Ten0** [gsquire/sendgrid-rs#38]
Right now building a simple mail is so much boilerplate. 

- [ ] They should provide `with_xx` constructors
- [ ] They should allow for `let x = X::new().add_something().add_something_else()` (`add_something(mut self) -> Self`)

**Comment by gsquire** [comment]
Again, this may fall in line with #30 so keep an eye out for that.

**Comment by gsquire** [comment]
Please let me know if version 0.8 didn't resolve this ticket by opening another. Thanks!
