### ISSUE TITLE
Unclear branching structure

### ISSUE THREAD

**Issue by otavio** [gsquire/sendgrid-rs#42]
My understanding is that `master` is intended to become the 0.8 release however the `0.7.x` branch and release tags are not pushed. 

Please take a look at this since it is hard to know where to look for checking for fixes and changes.

**Comment by gsquire** [comment]
This should be resolved once I publish 0.8 and we won't need to worry about the patches.

**Comment by gsquire** [comment]
[Version 0.8](https://crates.io/crates/sendgrid/0.8.0) has been published. Please open another issue if anything comes up.

Thanks for the support!
