### ISSUE TITLE
The library would benefit from simpler constructors and shortcuts

### ISSUE THREAD

**Issue by Ten0** [gsquire/sendgrid-rs#44]
Version 0.8 is so much better to use than before ! (#43)
However, not allowing to use `Email::new()` without passing an `email` would make more sense in my opinion, since the "Email" concept doesn't really exist if it is not set (as is very well held by the `Email` struct typing), so we shouldn't allow building an `Email` struct and forgetting to set the `email` field of that struct.
As a consequence, I would replace the :
```rust
sg::Email::new()
	.set_email("some@mail.com")
	.set_name("Some Person")
```
by :
```rust
sg::Email::new("some@mail.com") // Possibly still allow set_name but chances are it wouldn't be needed by any clean code
// and
sg::Email::with_name("some@mail.com", "Some Person")
```
and remove the `Default` derive on that type.

In a similar fashion :
```rust
sg::Personalization::with_to(email)
// as an additional constructor for
sg::Personalization::new().add_to(email)
```
and
```rust
sg::Message::new().add_to(email)
// as a helper for
sg::Message::new().add_personalization(sg::Personalization::new().add_to(email))
```
would make the library even less verbose and more practical to use.

**Comment by gsquire** [comment]
I wouldn't be opposed to adding some of these niceties to a separate module. I will be able to experiment with this in the coming weeks.
