### ISSUE TITLE
when SG returns error, library happily returns success

### ISSUE THREAD

**Issue by kanekv** [gsquire/sendgrid-rs#50]
Hey @gsquire, I've tried to send message and it returned Ok with the following error:
```
{"errors":[{"message":"If present, text/plain must be first, followed by text/html, followed by any other content.","field":"content","help":null}]}
```

I wonder if SG returns successful status code in this case?

**Comment by kanekv** [comment]
Did a quick check and SG does return 400. I think it would make sense to check if response anything else than 200 and return an error instead.

**Comment by kanekv** [comment]
Let me know how you want to approach this and I might provide a PR.

**Comment by gsquire** [comment]
Hey, Kane. I didn't do any status checking so I would be happy to integrate that in.

**Comment by kanekv** [comment]
@gsquire main question do we return response text verbatim or try to decode json?

**Comment by gsquire** [comment]
Perhaps we can make a new error type for unsuccessful responses and return that? So you could parse the JSON and return the actual status.
