### ISSUE TITLE
`RequestNotSuccessful` lacks error details

### ISSUE THREAD

**Issue by Ten0** [gsquire/sendgrid-rs#66]
I'm getting this error:
https://github.com/gsquire/sendgrid-rs/blob/21bd46546bf36505e9c834182ed453517fdc72a3/src/errors.rs#L30-L31

But the way display is implemented does not allow me to get the error message, and as a consequence it's hard to figure out why my emails don't send (I have to update my code to turn it into an error that actually shows the body).

I think it would be great if some form of additional information could be extracted from the body and used in the Display impl, so it would be easier to figure out why the emails don't send.

**Comment by gsquire** [comment]
I think that's a reasonable ask. I didn't originally include it because I expect there to be many different types of errors that can happen. I'd be willing to review a PR or I'll try and make a patch soon.
