### ISSUE TITLE
Personalization requires at least one email which isn't convenient

### ISSUE THREAD

**Issue by GopherJ** [gsquire/sendgrid-rs#79]

**Comment by GopherJ** [comment]
I just noticed that since certain commit, `Personalization` needs to provide at least one email, this isn't convenient.

Because in one email we often have multiple receivers, it's normal to build an empty Personalization and then loop through the list of receivers.

However, with the latest change, we need to do:

```rust
let mut p = Personalization::new(Email::new(receivers.remove(0))

p.add_to(..)
```

**Comment by gsquire** [comment]
Hey, sorry that this is a little bit of a paper cut for the API. I'd be willing to add an `Email::many` API that accepts a vector of receivers if that would help.

**Comment by gsquire** [comment]
I'm closing this since the work has been done. Feel free to re-open or make a new issue otherwise.
