### ISSUE TITLE
Support for either `pub add_field` or `add_template_id`

### ISSUE THREAD

**Issue by seenickcode** [gsquire/sendgrid-rs#81]
It seems like it's not possible to set the template ID when sending a mail Is that correct?

**Comment by gsquire** [comment]
Which version of the SendGrid API are you using? [Here](https://docs.rs/sendgrid/*/sendgrid/v3/struct.Message.html#method.set_template_id) is the function you can use for V3.

**Comment by seenickcode** [comment]
Works. Thanks. Looks like I was looking at the example in [`main.rs`](https://docs.rs/crate/sendgrid/0.15.0/source/examples/main.rs) which sadly, seems to not use the `v3` module.
