### ISSUE TITLE
Update to `reqwest` 0.11

### ISSUE THREAD

**Issue by ecclarke42** [gsquire/sendgrid-rs#82]
Hi!

I'm using this library for a project at work and just upgraded our server to use the `tokio` 1.0 runtime. Sending emails has broken with that change, showing a "not currently running on the Tokio runtime" error, so it seems like `reqwest`'s `tokio` version needs to match whatever is running.

Luckily, this should not require any code changes (just bumping `reqwest` and `tokio` versions), but might require a version change/new release on crates.io.

**Comment by gsquire** [comment]
Yeah, `tokio` 1.0 isn't compatible with the older runtime versions so this would indeed happen. Thanks for the patch!

**Comment by ecclarke42** [comment]
No problem! This (small as it was) was my first open-source PR, so it was a great way to dip my toes in the water and get something useful done for work at the same time!
