### ISSUE TITLE
form_encoder

### ISSUE THREAD

**Issue by deckarep** [gsquire/sendgrid-rs#9]
@gsquire 

What do you think about using this library for the building of the form encoded data during creation of the message body?

[dependencies]
url = "1.0.0"

```
extern crate url;
use url::form_urlencoded;

fn main() {
    let encoded: String = form_urlencoded::Serializer::new(String::new())
          .append_pair("to[]", "bob@example.com")
          .append_pair("saison", "Été+hiver")
          .finish();
    println!("{:?}", encoded);
}
```

Output: to%5B%5D=bob%40example.com&saison=%C3%89t%C3%A9%2Bhiver

**Comment by deckarep** [comment]
Actually, now that I think about this...using a library like this would be redundant with the underlying library that's making the post.  Which I assumes converts the body into form encoded data or it wouldn't work properly.  

I'm trying to see if there's a way to get rid all the string concatenation happening.

**Comment by gsquire** [comment]
I don't think hyper will actually encode the post body leaving it up to the user. So I think this library will work well especially for special characters. If you want to open a PR, that would be sweet.

**Comment by deckarep** [comment]
Cool I'll try to get something started.
